---
- name: Setup EC2 with MySQL, PostgreSQL, and Nginx
  hosts: web
  become: true

    #vars:
    # mysql_root_temp_password: ""
    #mysql_root_password: "YourSecureRootPassword"

  roles:
    - mysql
    - postgres
    - nginx
    - docker-swarm

  handlers:
    - name: Restart MySQL
      systemd:
        name: mysql
        state: restarted

    - name: Restart PostgreSQL
      systemd:
        name: postgresql
        state: restarted

