- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

- name: Add Docker GPG key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/docker-archive-keyring.gpg

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu focal stable
    filename: docker
    state: present

- name: Install Docker engine
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Enable and start Docker
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Initialize Docker Swarm
  shell: docker swarm init
  register: swarm_init
  failed_when: swarm_init.rc != 0 and 'This node is already part of a swarm' not in swarm_init.stderr
  changed_when: "'Swarm initialized' in swarm_init.stdout"

- name: Copy Docker Compose file for Hello World app
  copy:
    dest: /opt/hello-world-docker-compose.yml
    content: |
      version: "3"
      services:
        hello:
          image: nginxdemos/hello
          ports:
            - "8080:80"

- name: Deploy Hello World app using Docker Compose
  shell: docker stack deploy -c /opt/hello-world-docker-compose.yml hellostack
  args:
    chdir: /opt

