- name: Install PostgreSQL and contrib package
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - postgresql
    - postgresql-contrib

- name: Enable and start PostgreSQL
  systemd:
    name: postgresql
    enabled: true
    state: started

- name: Configure PostgreSQL to listen on all addresses
  lineinfile:
    path: /etc/postgresql/16/main/postgresql.conf
    regexp: '^#?listen_addresses'
    line: "listen_addresses = '*'"
    backup: yes
  notify: Restart PostgreSQL

- name: Allow external connections in pg_hba.conf
  lineinfile:
    path: /etc/postgresql/16/main/pg_hba.conf
    insertafter: '^# IPv4 local connections:'
    line: "host    all             all             0.0.0.0/0               md5"
    backup: yes
  notify: Restart PostgreSQL

